spring:
  message: Este es el profile de desarrollo

ar:
  com: algo
  
  
#  datasource:
#     db-Pruebas:
#        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#        url: jdbc:sqlserver://localhost:1433;databaseName=Pruebas   
#        user: mrsoria
#        password: Test2208
#        jpa:
#          hibernate:
#            ddl-auto: update
#          show-sql: true
#          properties:
#             hibernate:
#                format_sql: true
#                dialect: org.hibernate.dialect.SQLServer2012Dialect    
#
#     db-config-batch:
#        driver-class-name: org.h2.Driver
#        url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
#        username: admin
#        password:
    
